#!/bin/sh

# Remove files used by the building and installation that are not
# needed to use redland.

pkg_dir=${R_LIBRARY_DIR}/${R_PACKAGE_NAME}

if [ ! -z $pkg_dir ] && [ -d ${pkg_dir}/testfiles ] ; then
    rm -rf ${pkg_dir}/testfiles
fi